### ISSUE TITLE
Отсутствие документации к классам

### ISSUE THREAD

**Issue by Dnnd** [zwirec/TravelMate#10]
Критерий качества: удобство сопровождения

Следующие классы не имеют какой-либо документации:

- [managers](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/managers.h)
- [dbConfig](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/utils/dbConfig.h)
- [UserModel](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.h)
- [UserManager](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/managers/userManager.h)

**Comment by zwirec** [comment]
TODO
