### ISSUE TITLE
Передача строк по значению в методах класса WebSite

### ISSUE THREAD

**Issue by Dnnd** [zwirec/TravelMate#11]
Критерий качества: эффективность

Следующие методы класса WebSite принимают в качестве параметра копию строки:
[WebSite::news(std::string)](https://github.com/zwirec/TravelMate/blob/dev_nd-r/main.cpp#L54)
[WebSite::master(std::string)](https://github.com/zwirec/TravelMate/blob/dev_nd-r/main.cpp#L44)
[WebSite::main(std::string)](https://github.com/zwirec/TravelMate/blob/dev_nd-r/main.cpp#L30)

**Comment by zwirec** [comment]
FIXED
