### ISSUE TITLE
Валидация входных параметров при работе с БД 

### ISSUE THREAD

**Issue by Dnnd** [zwirec/TravelMate#12]
Критерий качества: безопасность
Добавление информации в базу данных осуществляется без проверки входных данных

- [userManager::authenticate()](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/managers/userManager.cpp#L23)
- [userManager::create()](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/managers/userManager.cpp#L65)

Конструкторы UserModel так же не проверяют входные данные
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp#L13](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp#L13)
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp#L18](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp#L18)
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp#L13](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp#L13)

**Comment by zwirec** [comment]
1. TODO
