### ISSUE TITLE
Ограничение типов исключений, генерируемых функцией

### ISSUE THREAD

**Issue by DrMatters** [zwirec/TravelMate#13]
Критерий качества: надежность
1) На методы класса userManager можно наложить ограничения на типы генерируемых исключений:
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/managers/userManager.h](url)
2) На методы класса UserModel.h можно наложить ограничения на типы генерируемых исключений:
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/UserModel.h](url)

**Comment by zwirec** [comment]
TODO
