### ISSUE TITLE
Магические константы

### ISSUE THREAD

**Issue by Dnnd** [zwirec/TravelMate#3]
Критерий качества: удобство сопровождения

1. Макрос  sql_create_3, литералы 2 и 3
 [https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/userPrototype.h#L17](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/userPrototype.h#L17)

2. Макрос  sql_create_4, литералы 2 и 4
 [https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/userPrototype.h#L17](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/userPrototype.h#L17)

3. Размер по-умолчанию для поля vector структуры Master, литерал 8
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/data/tmpl_master.h#L39](https://github.com/zwirec/TravelMate/blob/dev_nd-r/data/tmpl_master.h#L39)

4. Сумма литералов 64 и 9 сравнивается с password.size(),
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp#L14](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp#L14)
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp#L20](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp#L20)
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp#L25](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp#L25)

5. Cтроковый литерал ":sha256::" как аргумент для password.find()
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp#L14](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp#L14)
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp#L20](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp#L20)
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp#L25](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp#L25)

**Comment by zwirec** [comment]
1. FIXED

**Comment by zwirec** [comment]
1. FIXED
2. REMOVE
3. REMOVE
4. FIXED
5. FIXED
