### ISSUE TITLE
Неинформативные имена компонентов

### ISSUE THREAD

**Issue by Dnnd** [zwirec/TravelMate#4]
Критерий качества: удобство сопровождения

1. Параметры конструктора класса UserModel
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.h#L17](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.h#L17)
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp#L13](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp#L13)

2. Название единственного метода класса manager (временное название?)
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/managers/manager.h#L11](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/managers/manager.h#L11)

3. Неиформативное (несодержательное) название namespace Data
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/data/tmpl_news.h](https://github.com/zwirec/TravelMate/blob/dev_nd-r/data/tmpl_news.h)

4. Несодержательное название атрибута Master::vector
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/data/tmpl_master.h#L39](https://github.com/zwirec/TravelMate/blob/dev_nd-r/data/tmpl_master.h#L39)

**Comment by zwirec** [comment]
1. FIXED
2. YES
3. TODO
4. REMOVED
