### ISSUE TITLE
Одинаково названные файлы и каталоги в структуре проекта

### ISSUE THREAD

**Issue by Dnnd** [zwirec/TravelMate#5]
Критерий качества: удобство сопровождения (очень сильно усложняется code review)

1. файлы UserModel.h 
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/UserModel.h](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/UserModel.h)
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.h](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.h)

2. файлы UserModel.cpp
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp)
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/UserModel.cpp](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/UserModel.cpp)

3. каталог managers
[https://github.com/zwirec/TravelMate/tree/dev_nd-r/managers](https://github.com/zwirec/TravelMate/tree/dev_nd-r/managers)
[https://github.com/zwirec/TravelMate/tree/dev_nd-r/managers/managers](https://github.com/zwirec/TravelMate/tree/dev_nd-r/managers/managers)

6. Файлы userPrototype.h
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/userPrototype.h](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/userPrototype.h)
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/userPrototype.h](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/userPrototype.h)

**Comment by zwirec** [comment]
FIXING SOON
