### ISSUE TITLE
Const-корректность

### ISSUE THREAD

**Issue by Dnnd** [zwirec/TravelMate#6]
Критерий качества: надежность, производительность
1. Метод `managers::getManager()` может быть объявлен как const
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/managers.h#L25](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/managers.h#L25)
2.` loginEquality::operator()` может быть объявлен как const 
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/managers/userManager.cpp](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/managers/userManager.cpp)
3. `WebSite::print()` может быть объявлен как const 
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/main.cpp#L38](https://github.com/zwirec/TravelMate/blob/dev_nd-r/main.cpp#L38)

**Comment by zwirec** [comment]
1.FIXED
2.FIXED
3.REMOVED
