### ISSUE TITLE
Дублирование кода

### ISSUE THREAD

**Issue by Dnnd** [zwirec/TravelMate#7]
Критерийрий качества: удобство сопровождения

1. Конструкторы класса UserModel имеют одинаковое тело
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp#L13](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp#L13)
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp#L18](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp#L18)
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp#L24](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.cpp#L24)

2. Перегрузки метода ` manager<>::create(...)` почти идентичны в реализации
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/managers/userManager.cpp#L65](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/managers/userManager.cpp#L65)
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/managers/userManager.cpp#L73](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/managers/userManager.cpp#L73)
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/managers/userManager.cpp#L88](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/managers/userManager.cpp#L88)

3. Перегрузки метода` manager<>::authenticate(...) ` почти идентичны в реализации
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/managers/userManager.cpp#L45](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/managers/userManager.cpp#L45)
[https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/managers/userManager.cpp#L23](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/managers/userManager.cpp#L23)

**Comment by zwirec** [comment]
REFUSED
