### ISSUE TITLE
Несогласованность сообщений об ошибках в классе UserModel

### ISSUE THREAD

**Issue by Dnnd** [zwirec/TravelMate#8]
Критерий качества: безопасность, удобство сопровождения
В метод класса `manager<>::authenticate(...)` сообщения об ошибках содержат текст как на [русском](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/managers/userManager.cpp#L37), так и на [английском ](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/managers/userManager.cpp#L27) языках.

**Comment by zwirec** [comment]
DELETED
