### ISSUE TITLE
Отсутствие спецификатора explicit

### ISSUE THREAD

**Issue by Dnnd** [zwirec/TravelMate#9]
Критерий качества: надежность

Конструкторы следующих классов принимают один аргумент и  не объявлены как explicit:

- [UserModel](https://yZ.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.h#L20)
- [manager<UserModel>](https://github.com/zwirec/TravelMate/blob/dev_nd-r/managers/models/user/UserModel.h#L20)
- [WebSite ](https://github.com/zwirec/TravelMate/blob/dev_nd-r/main.cpp#L18)

**Comment by zwirec** [comment]
# FIXED SOON
